#!/usr/bin/php
<?php

use Gnugat\RedaktiloBundle\DependencyInjection\CommandCompilerPass;
use Gnugat\RedaktiloBundle\DependencyInjection\SearchStrategyCompilerPass;
use Monolog\Logger;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

require __DIR__.'/vendor/autoload.php';

$container = new ContainerBuilder();
$container->setParameter('fossil.version', '@package_version@');
$container->setParameter('fossil.path.skeletons', __DIR__.'/skeletons');
$container->setParameter('monolog.console_handler.verbosity_level_map', array(
    OutputInterface::VERBOSITY_NORMAL => Logger::NOTICE,
    OutputInterface::VERBOSITY_VERBOSE => Logger::INFO,
    OutputInterface::VERBOSITY_VERY_VERBOSE => Logger::DEBUG,
    OutputInterface::VERBOSITY_DEBUG => Logger::DEBUG,
));

$internalLoader = new YamlFileLoader($container, new FileLocator(__DIR__.'/src/Gnugat/Fossil/dic'));
$internalLoader->load('services.yml');

$redaktiloLoader = new YamlFileLoader($container, new FileLocator(__DIR__.'/vendor/gnugat/redaktilo-bundle/Resources/config'));
$redaktiloLoader->load('services.yml');
$container->addCompilerPass(new SearchStrategyCompilerPass());
$container->addCompilerPass(new CommandCompilerPass());

$output = $container->get('symfony.console.output');

$application = $container->get('symfony.console.application');
$application->run(null, $output);
